# archivo de despliegue para la aplicación legacy
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-legacy
  labels:
    app: apps
    component: legacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps
      component: legacy
  template:
    metadata:
      labels:
        app: apps
        component: legacy
    spec:
      containers:
      - name: app-legacy
        image: final_ds-app-legacy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB