apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-microservice
  labels:
    app: unified-apps
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unified-apps
      component: microservice
  template:
    metadata:
      labels:
        app: unified-apps
        component: microservice
    spec:
      containers:
      - name: new-microservice
        image: final_ds-new-microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: API_KEY
        - name: LEGACY_APP_URL
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: LEGACY_APP_URL