apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-microservice
  labels:
    app: new-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-microservice
  template:
    metadata:
      labels:
        app: new-microservice
    spec:
      containers:
      - name: new-microservice
        image: final_ds-new-microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: API_KEY
        - name: LEGACY_APP_URL
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: LEGACY_APP_URL
---
apiVersion: v1
kind: Service
metadata:
  name: new-microservice-service
spec:
  selector:
    app: new-microservice
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP