apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  # información de acceso a la base de datos formato Base64
  POSTGRES_USER: dXNlcg== # user
  POSTGRES_PASSWORD: cGFzcw== # pass
  POSTGRES_DB: ZGI= # db